name: First Workflow
on: [push]

jobs:
  run-shell-coomands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Owrld"
      - name: Multiline commands
        run: |
          node -v
          npm -v
  parallel-jobs-macos:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependant-jobs:
    runs-on: windows-latest
    needs: [run-shell-coomands]
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error step
        run: doesnotexistss
